module.exports = {
    MEGUMIN_DISCORD_TOKEN: process.env.MEGUMIN_DISCORD_TOKEN,

    ISONYAN_DISCORD_TOKEN: process.env.ISONYAN_DISCORD_TOKEN,

    KEYARG_DISCORD_TOKEN: process.env.KEYARG_DISCORD_TOKEN,

    NAGATORO_SAN_DISCORD_TOKEN: process.env.NAGATORO_SAN_DISCORD_TOKEN,
    NAGATORO_SAN_DISCORD_STALK: process.env.NAGATORO_SAN_DISCORD_STALK,

    NANACHI_DJ_DISCORD_TOKEN: process.env.NANACHI_DJ_DISCORD_TOKEN,
    NANACHI_DJ_DISCORD_PREFIX: process.env.NANACHI_DJ_DISCORD_PREFIX,
    NANACHI_DJ_TWITCH_CLIENT_ID: process.env.NANACHI_DJ_TWITCH_CLIENT_ID,
    NANACHI_DJ_TWITCH_CLIENT_SECRET: process.env.NANACHI_DJ_TWITCH_CLIENT_SECRET,

    MAYU_BOT_DISCORD_TOKEN: process.env.MAYU_BOT_DISCORD_TOKEN,

    TWITCH_CLIENT_ID: process.env.TWITCH_CLIENT_ID,
    TWITCH_CLIENT_SECRET: process.env.TWITCH_CLIENT_SECRET,

    PORT: process.env.PORT,
    DOMAIN: process.env.DOMAIN,

    NODE_ENV: process.env.NODE_ENV,

    // Testing
    DISCORD_TESTING_GUILD_ID: process.env.DISCORD_TESTING_GUILD_ID
}
