export default {
    NAGATORO_SAN_DISCORD_TOKEN: process.env.NAGATORO_SAN_DISCORD_TOKEN,
    NAGATORO_SAN_TWITCH_CLIENT_ID: process.env.NAGATORO_SAN_TWITCH_CLIENT_ID,
    NAGATORO_SAN_TWITCH_CLIENT_SECRET: process.env.NAGATORO_SAN_TWITCH_CLIENT_SECRET,
    NAGATORO_SAN_DISCORD_STALK: process.env.NAGATORO_SAN_DISCORD_STALK,

    NANACHI_DJ_DISCORD_TOKEN: process.env.NANACHI_DJ_DISCORD_TOKEN,
    NANACHI_DJ_DISCORD_PREFIX: process.env.NANACHI_DJ_DISCORD_PREFIX,
    NANACHI_DJ_TWITCH_CLIENT_ID: process.env.NANACHI_DJ_TWITCH_CLIENT_ID,
    NANACHI_DJ_TWITCH_CLIENT_SECRET: process.env.NANACHI_DJ_TWITCH_CLIENT_SECRET,
    YOUTUBE_API_KEY: process.env.YOUTUBE_API_KEY,
    SOUNDCLOUD_CLIENT_ID: process.env.SOUNDCLOUD_CLIENT_ID,
    MAX_PLAYLIST_SIZE: process.env.MAX_PLAYLIST_SIZE,
    PRUNING: process.env.PRUNING,
    STAY_TIME: process.env.STAY_TIME,
    DEFAULT_VOLUME: process.env.DEFAULT_VOLUME,

    WEBAPP_TWITCH_CLIENT_ID: process.env.WEBAPP_TWITCH_CLIENT_ID,
    WEBAPP_TWITCH_CLIENT_SECRET: process.env.WEBAPP_TWITCH_CLIENT_SECRET,

    PORT: process.env.PORT,
    DOMAIN: process.env.DOMAIN
}
